# Test the order-service

### Place an order
POST https://order-service-demo-gch4e6audgdhb8fk.canadacentral-01.azurewebsites.net/orders
Content-Type: application/json

{
  "product": "Cat Food",
  "price": "59.99$"
}
